version: "3"
services:
  mymongo:
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017

  mymongo-express:
    image: mongo-express
    container_name: mymongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mymongo
    restart: unless-stopped

  myapp:
    build: .
    image: ali1602/voiture-manage-app
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mymongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mymongo
      - SPRING_DATA_MONGODB_PORT=27017